blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from mysite.views import *


# from django.views.static import serve
# from django.conf import settings
#
# from haystack.views import SearchView

urlpatterns = [
    #jet后台
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    #搜索引擎
    # url(r'^search/', include('haystack.urls')),
    path('search/',MySeachView(),name='haystack'),
    # 验证码
    url(r'captcha/', include('captcha.urls')),


    path('admin/', admin.site.urls),
    path('mysite/',include('mysite.urls',namespace='mysite'))
]

mysite/urls.py
from django.urls import path
from .views import *


app_name='mysite'
urlpatterns=[
    path('',ArticleList.as_view(),name='articlelist'),
    path('article/<slug:slug>/',ArticleDetial,name='articledetial'),
    path('/share/<int:pk>/',article_share.as_view(),name='articleshare'),
    path('govote/<int:pk>/',govote,name='govote'),
]

mysite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from taggit.managers import TaggableManager
from slugify import slugify

# Create your models here.

class Articles(models.Model):
    CHOICE_STATUS=(
        ('草稿','草稿'),
        ('成文','成文'),
    )

    user=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    slug=models.SlugField(max_length=250,unique=True,blank=True)
    content=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created_time=models.DateTimeField(auto_now_add=True)
    change_time=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10,choices=CHOICE_STATUS,default='草稿')
    like=models.IntegerField(default=0)
    tags=TaggableManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering=['created_time']

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.slug=slugify(self.title)
        super(Articles, self).save()

class Comment(models.Model):
    article=models.ForeignKey(Articles,on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=['created']

    def __str__(self):
        return 'Comment {} by {}'.format(self.article,self.name)

mysite/forms.py
from django import forms
from .models import *
from captcha.fields import CaptchaField

class EmailForm(forms.Form):
    name=forms.CharField(max_length=125,label='名字')
    to=forms.EmailField(label='接收方')
    comments=forms.CharField(label='评论',required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model=Comment
        fields=['name','email','body']
    # def __init__(self):
    #     super(CommentForm, self).__init__()
    #     self.fields['body'].label = '评论'
    #     self.fields['name'].label = '尊姓大名'
    #     self.fields['email'].label = '您的邮箱地址'
    #     self.fields['captcha'].label = '确认你不是机器人'

mysite/views.py
from django.shortcuts import render,get_object_or_404,HttpResponse
from .models import Articles
from django.views.generic import RedirectView,View
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from .forms import EmailForm,CommentForm
from django.core.mail import send_mail
from django.conf import settings
from haystack.views import SearchView
from django.db.models import Q
import redis
from django.conf import settings
from django.views.decorators.http import require_http_methods

r=redis.StrictRedis(host=settings.REDIS_HOST,
                    port=settings.REDIS_PORT,
                    db=settings.REDIS_DB)
# Create your views here.


class ArticleList(View):
    # model = Articles
    # context_object_name = 'articles'
    # paginate_by = 1
    # template_name = 'mysite/articleList.html'
    def get(self,request):
        articles = Articles.objects.filter(user=request.user)
        pages = Paginator(articles, 5)
        page1=request.GET.get('page',None)
        try:
            page = pages.page(page1)
        except PageNotAnInteger:
            page = pages.page(1)
        except EmptyPage:
            page = pages.page(pages.num_pages)
        return render(request, 'mysite/articleList.html', locals())

@require_http_methods(['GET','POST'])
def ArticleDetial(request,slug):
    if request.method=='GET':
        article=get_object_or_404(Articles,slug=slug)
        comments=article.comment_set.filter(active=True)
        forms=CommentForm()

        article_tags=article.tags.values_list('id',flat=True)
        similar_articles=Articles.objects.filter(tags__in=article_tags).exclude(id=article.id)

        #????
        key='views:{}'.format(article.slug)
        vv = request.session.get(key, '')
        if not vv:
            '''???????views'''
            request.session[key] = str(request.user)
            request.session.set_expiry(0)  # ??????????
            total_views = r.incr('arricle:{}:views'.format(article.id))  # ??????1

        total_views = int(r.get('arricle:{}:views'.format(article.id)))
        r.zincrby('article_ranking', article.id, 1)
        article_ranking = r.zrange('article_ranking', 0, -1, desc=True)[:5]
        article_ranking_ids = [int(id) for id in article_ranking]
        most_viewed = list(Articles.objects.filter(id__in=article_ranking_ids))
        most_viewed.sort(key=lambda x: article_ranking_ids.index(x.id))

        return render(request,'mysite/articleDetial.html',locals())
    else:
        forms=CommentForm(request.POST)
        article = get_object_or_404(Articles, slug=slug)
        comments = article.comment_set.filter(active=True)
        if forms.is_valid():
            new_comm=forms.save(commit=False)
            new_comm.article=article
            new_comm.save()
            msg='????'
            return render(request, 'mysite/articleDetial.html', locals())

class article_share(View):
    def get(self,request,pk):
        article=get_object_or_404(Articles,id=pk)
        form=EmailForm()
        return render(request,'mysite/share.html',locals())

    def post(self,request,pk):
        article=get_object_or_404(Articles,id=pk)
        form=EmailForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            article_url='https://127.0.0.1:8000/mysite/article/'+article.slug
            subject='{} recommendss you reading?'.format(article.title)
            message='Read {} at {}'.format(article.title,article_url)
            send_mail(subject,message,settings.DEFAULT_EMAIL_FROM,[cd['to']])
            return render(request, 'mysite/share.html', locals())

#??
#??????????????
#??????????
class MySeachView(SearchView):
    template = 'search/search.html'

    def extra_context(self):       #??extra_context??????context??
        context = super(MySeachView,self).extra_context()
        a=self.form.cleaned_data['q']
        articles = Articles.objects.filter(Q(title__icontains=a)|Q(content__icontains=a)).order_by('created_time')[:8]
        context['articles'] = articles
        return context

def govote(request,pk):
    if request.method=='GET' and request.is_ajax():
        try:
            article=Articles.objects.get(id=pk)
            article.like=article.like+1
            article.save()
            like=article.like
        except:
            like=0
    else:
        like=0
    return HttpResponse(like)

templates/mysite/articleDetial.html
{% extends 'mysite/base.html' %}
{% load cache %}

    {% block extra_head %}
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    {% endblock %}
{% block content %}
    <script>
        $(document).ready(function () {
            $("#btn-{{ article.id }}").click(function () {
                alert('ok');
                $.ajax({
                        type:'GET',
                        url:'/mysite/govote/{{ article.id }}',
                        data:{
                            'pollitemid':{{ article.id }}
                        },
                        success:function (like) {
                            if(like==0){
                                alert('无法投票');
                            }else{
                                $('#pollitem-{{ article.id }}').html(like);
                                alert('投票成功！')
                            }
                        }
                    });
                });
        })
    </script>
    {#    {% cache 500 sidebar  %}#}
    <div class="col-md-9">
        <h1 class="text-center">{{ article.title }}</h1>
        <p>Views：{{ total_views }}</p>
        {% for t in article.tags.all %}
            <span class="label label-success text-center">{{ t }}</span>
        {% endfor %}

        <p class="datetime">
            Published {{ article.publish }} by {{ article.user }}
        </p>
        <hr>
        {{ article.content|linebreaks }}
        <button type="button" class="btn btn-default btn-lg" id="btn-{{ article.id }}">
          <span class="glyphicon glyphicon-star" aria-hidden="true"
                id="pollitem-{{ article.id }}">{{ article.like }}</span> Star
        </button>
    {#    {% endcache %}#}
    </div>

    <div class="col-md-3">
        <h2>相似帖子</h2>
        {% for p in similar_articles %}
            {#        <a href="{% url 'mysite:articledetial' p.slug %}">{{ p.title }}</a>#}
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'mysite:articledetial' p.slug %}">{{ p.title }}</a></li>
            </ul>
        {% empty %}
            <p>没有类似帖子</p>
        {% endfor %}

        <h2>最受欢迎的文章</h2>
        <ul class="list-group">
            {% for a in most_viewed %}
                <li class="list-group-item"><a href="{% url 'mysite:articledetial' a.slug %}">{{ a.title }}</a></li>
            {% endfor %}
        </ul>

        <p>我来评论：</p>
        <form action="." method="post">
            {% csrf_token %}

                {{ forms.as_table }}
                <button type="submit" class="btn btn-success">评论</button>

        </form>
        <hr>
        {% for c in comments %}
            <div class="comment">
                <p class="info">
                    评论 {{ forloop.counter }} 来自 {{ c.name }}
                </p>
                {{ c.body|linebreaks }}
            </div>
        {% empty %}
            <p>暂时无人评论</p>
        {% endfor %}

        <hr>
        <a href="{% url 'mysite:articleshare' article.id %}">分享帖子</a>

{% endblock %}

templates/mysite/articleList.html
{% extends 'mysite/base.html' %}
{% load mysite_tags %}

{% block content %}
    <h1 class="text-center">我的个人小站</h1>
    <section class="col-md-5">
        {% for a in articles %}
            <h2>
            <a href="{% url 'mysite:articledetial' a.slug %}">{{ a.title }}</a>
            </h2>
            {% for t in a.tags.all %}
                <span class="label label-success">{{ t}}</span>
                {% endfor %}
            <p class="datetime">
            Published {{ a.publish }} by {{ a.user }}
            </p>
            {{ a.content|truncatechars:30|linebreaks }}
        {% endfor %}
    {% include 'mysite/paginator.html' with page=page_obj %}
    </section>
    <section class="col-md-4">
    {% show_latest_articles  %}
    </section>
    <section class="col-md-4">
    {% mostcomment_articles %}
    </section >
    <section class="col-md-4">
    {% date_articles %}
    </section >
{% endblock %}

templates/mysite/base.html
{% load staticfiles %}
{% load mysite_tags %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/twitter-bootstrap/3.0.3/css/bootstrap.min.css">
    <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    {% block extra_head %}
    {% endblock %}
</head>
<body>
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/mysite">博客主页</a>
    </div>

      <form class="navbar-form navbar-left" action="/search" method="get">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Search" name="q">
        </div>
            <input type="submit"  value="搜索">
      </form>

    </div><!-- /.navbar-collapse -->

</nav>
</header>
    <div class="container">
        <div class="row">
        {% block content %}

        {% endblock %}
        </div>
    </div>

<footer>
    <address class="text-center">
          <strong>LoseNine.</strong><br>
          created by Django<br>
    </address>
</footer>
</body>

</html>

templates/mysite/date_article.html
{% load mysite_tags %}
<div class="text-right">
    <span class="label label-primary">归档</span>
    <ul>
    {% for y in year %}
        <ul>年份<p>{{ y }}</p>
            {% for a in date_articles %}
                {% if a.created_time.year == y %}
                    <li class=" text-right list-unstyled">
                     <a href="{% url 'mysite:articledetial' a.slug %}">{{ a.title}}</a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endfor %}

</ul>
</div>

templates/mysite/latest_article.html
<div class="text-right">

<span class="label label-danger">最新帖子</span>
    <ul>
    {% for post in latest_article %}
     <li class=" text-right list-unstyled">
         <a href="{% url 'mysite:articledetial' post.slug %}">{{ post.title}}-{{ post.created_time }}</a>
     </li>
    {% endfor %}
</ul>
</div>

templates/mysite/mostcomment_article.html
{% load mysite_tags %}
<div class="text-right">

<span class="label label-warning">评论最多</span>
    <ul>
    {% for post in mostcomment_articles %}
     <li class=" text-right list-unstyled">
         <a href="{% url 'mysite:articledetial' post.slug %}">{{ post.title}}-{{ post.slug|total_comment }}条评论</a>
     </li>
    {% endfor %}
</ul>
</div>

templates/mysite/paginator.html
<nav aria-label="Page navigation" class="text-center">
  <ul class="pagination">
    <li>
        {% if page.has_previous %}
        <a href="?page={{ previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
          {% endif %}
      </a>
    </li>
  {% for pp in pages.page_range %}
      {% if pp == page.number %}
    <li><a href="#">{{ pp }}</a></li>
      {% else %}
    <li><a href="?page={{ pp }}">{{ pp }}</a></li>
       {% endif %}
       {% endfor %}
    <li>
        {% if page.has_next %}
      <a href="/mysite/?page={{ page.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
        {% endif %}
    </li>
  </ul>
</nav>

templates/mysite/share.html
{% extends 'mysite/base.html' %}

{% block content %}
{% if sent %}
    <h1>E-mail successfully</h1>
    <p>{{ article.title }} was successfully sent to {{ cd.to }}</p>
    {% else %}
    <h1>分享 {{ article.title }} by e-mail</h1>

    <form action="." method="post">
    {% csrf_token %}
      <div class="form-group">
        <label for="name">你的名字</label>
        <input type="password" class="form-control" id="name" name="name" placeholder="无名" >
      </div>
      <div class="form-group">
        <label for="to">对方的Email 地址</label>
        <input type="email" class="form-control" id="to" name='to' placeholder="Email">
      </div>
      <div class="form-group">
        <label for="text">评论</label>
        <textarea class="form-control" id='text' name='comments' rows="3"></textarea>
      </div>
      <button type="submit" class="btn btn-success" >评论</button>
    </form>
{% endif %}


{% endblock %}

templates/search/search.html
{% extends 'mysite/base.html' %}
{% block content %}
    <h1 class="center">搜索结果如下</h1>
        {% for a in articles %}
            <h2>
            <a href="{% url 'mysite:articledetial' a.slug %}">{{ a.title }}</a>
            </h2>
            {% for t in a.tags.all %}
                <span class="label label-success">{{ t}}</span>
                {% endfor %}
            {{ a.content|truncatechars:30|linebreaks }}
        {% endfor %}

{% endblock %}

templates/search/search1.html
{% extends 'mysite/base.html' %}
{% block content %}
    <h2 class="center">Search</h2>

<ul class="sr-only">
{% if show_all %}
{% for item in page.object_list %}
<li>
    <div>
        <div>
            {{ item.title }}
        </div>
        <div>{{ item.user }}</div>
        <div>{{ item.created_time }}</div>
    </div>
</li>
{% endfor %}
{% else %}
{#自动高亮#}
{% load highlight %}
{% for itme in page.object_list %}
<li>
    <div>
        <div>{% highlight item.object.title with query %}</div>
    </div>
    <div>{{ item.object.user }}</div>
    <div>{% highlight item.object.created_time with query %}</div>
</li>
    {% endfor %}
</ul>
    {% endif %}
{% endblock %}